# Generated by Django 3.2.15 on 2022-09-21 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FormsTarefa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=25)),
                ('descricao', models.TextField()),
                ('status', models.CharField(max_length=25)),
                ('projeto', models.CharField(max_length=25)),
            ],
        ),
    ]
